### ISSUE TITLE
Seekbar Issue

### ISSUE THREAD

**Issue by DineshkumarKandasamy** [aws-samples/amazon-ivs-dvr-ios-demo#8]
Hi @slawrence In the sample url, we are not facing any issues. But, while we test with our ivs url, while we seek the seek bar to left end, some times it comes to the right end. It occurs randomly. Could you please suggest how we can over come this issue.

**Comment by DineshkumarKandasamy** [comment]
Hi @slawrence Any update?

**Comment by slee-aws** [comment]
Hi @DineshkumarKandasamy, sorry to hear you are having this issue. I am not able to reproduce the issue you described. Could you provide the following information to help us better diagnose the cause?

1. What streaming software are you using to stream?
2. Do you noticing any network issues while streaming?
3. What device and on which version of iOS are you seeing the issue?

**Comment by DineshkumarKandasamy** [comment]
Hi @slee-aws Thanks for the response. Kindly check the details below,
1. What streaming software are you using to stream? - Wowza
2. Do you noticing any network issues while streaming? - No
3. What device and on which version of iOS are you seeing the issue? - In all iOS devices above iOS 16 version

**Comment by slee-aws** [comment]
@DineshkumarKandasamy thank you for your response. We recently pushed an update to the [Amazon IVS DVR Web Demo](https://github.com/aws-samples/amazon-ivs-dvr-web-demo) that may alleviate this issue. Please pull the latest changes in that repository and re-deploy the server app.

**Comment by DineshkumarKandasamy** [comment]
Hi @slee-aws Thanks for the update. Actually we are facing the issue in mobile end. We have integrated IVS player in our project as similar like ios demo project. But ios demo project itself we are facing above issue while we check with live url. Kindly support on this.

**Comment by slee-aws** [comment]
@DineshkumarKandasamy Since you are experiencing the issue in your own application and not this demo, it will require additional input and guidance from our service teams. To help investigate this further, please open a support case with AWS Support or reach out and work with you your AWS account team to seek further assistance on the issue. They may be able to investigate the specific resources with which you are having trouble. 

If you neither have access to AWS Support and/or Account Teams, please post the question to [AWS re:Post](https://www.repost.aws/tags/TAAkUVScqiTFmkt-h6LdmJHw/amazon-interactive-video-service) where our developer advocates may provide additional insights. Thank you!
