### ISSUE TITLE
Seekbar not Updating..!!

### ISSUE THREAD

**Issue by rishopbabu** [aws-samples/amazon-ivs-dvr-ios-demo#9]
Seekbar is not properly updated in the player, with its dvr url. 
Can you please help me with this. Thanks in advance.

**Comment by mboulin** [comment]
Hi @rishopbabu . Thanks for opening the issue. Could you provide more details so that we can confirm this is indeed an issue with the demo?

- Could you describe the problem you are seeing in more details? The seek bar in the demo is behaving as expected on our side.
- What version of the player SDK are you using?
- Is this issue observable on all iOS versions/devices, or a specific device/version?
- Is this issue happening with a particular stream or all streams? ie. the included demo stream, or your own?
- Can you collect debug logs when this issue is observed?
- Can you describe your network conditions? Are you experiencing frequent disconnects due to poor network?

**Comment by rishopbabu** [comment]
Hi @mboulin,
1. while using our ivs dvr url, the seekbar is not is moved, but it is not moving according to timer & even the timer is also freezes. And sometimes when we move the seek bar to the left corner it plays the live recording. 
2. version of the player SDK -  1.18.0
3. iOS versions - iOS 16.4, devices: iPhone SE2, iPhone 11( so far tested devices).
4. issue happening with a particular stream or all stream - yes.
5. Can you collect debug logs when this issue is observed? - No
6. Network is well and good. No I did't face any frequent disconnects

**Comment by mboulin** [comment]
@rishopbabu thank you. Can you confirm that you have deployed and are using the serverless backend required: https://github.com/aws-samples/amazon-ivs-dvr-web-demo ?
This demo will not work without this backend, as described in the README.

Can you also confirm that you are using this demo with Amazon IVS? And if so, which channel type are you using, and in which region?

**Comment by rishopbabu** [comment]
Hi @mboulin Thanks for your reply. 
Here are the details,
- Can you confirm that you have deployed and are using the serverless backend required - **Yes we developed as per the readme documentation**
- Can you also confirm that you are using this demo with Amazon IVS - **Yes**
- which channel type are you using, and in which region? 
            **For Production server:**
            **Channel type - Standard** 
            **Region - us-east-1**
            **For Test server:**
            **Channel type - Basic**
            **Region - us-east-1**

**Comment by mboulin** [comment]
@rishopbabu thank you for the details! 
Could you pull the latest changes from this repo, build the app again, and give it another try?

**Comment by rishopbabu** [comment]
@mboulin Thank you, this issue fixed and working fine. I got one more issue, When we tap on forward and backward (60 secs) button, current live video is playing. can you please check on it?

**Comment by mboulin** [comment]
Closing this issue as it is resolved. 
Please open a new issue regarding the forward/backward button if you think this is related to the demo. If you do create a new issue, please provide as much details as possible.
